In [8]:
import pandas as pd

In [9]:
data = {
    'age' : [21,23,45,67,12,15],
    'money' : [1000000,240000,2300000,3400000,2340000,23500000]
}
data

{'age': [21, 23, 45, 67, 12, 15],
 'money': [1000000, 240000, 2300000, 3400000, 2340000, 23500000]}

In [10]:
dataframe = pd.DataFrame(data)
dataframe

   age     money
0   21   1000000
1   23    240000
2   45   2300000
3   67   3400000
4   12   2340000
5   15  23500000

In [11]:
dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     6 non-null      int64
 1   money   6 non-null      int64
dtypes: int64(2)
memory usage: 228.0 bytes

In [12]:
dataframe['age'] = dataframe['age'].astype('int8')
dataframe['money'] = dataframe['money'].astype('int32')
dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     6 non-null      int8
 1   money   6 non-null      int32
dtypes: int32(1), int8(1)
memory usage: 162.0 bytes

In [13]:
data2 = {
    'time' : ['2026-5-13','2026-5-20','2026-5-15']
}
timess = pd.to_datetime(data2["time"])
dataframe3 = pd.DataFrame(timess,columns=[['Date']])
dataframe3

        Date
0 2026-05-13
1 2026-05-20
2 2026-05-15