In [1]:
#install pandas
!pip install pandas

Requirement already satisfied: pandas in c:\users\rimon\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\rimon\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rimon\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rimon\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rimon\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\rimon\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
#import panda
import pandas as pd

In [9]:
# creat a list
data = [1,2,3,4,5]
data
type(data)

list

In [10]:
#create a series
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [14]:
#creat a dataframe by series
dataframe = pd.DataFrame(series,columns = ['num'])
dataframe

   num
0    1
1    2
2    3
3    4
4    5

In [16]:
#dataframe from data
dataframe2 = pd.DataFrame(data,columns = ['num'])
dataframe2

   num
0    1
1    2
2    3
3    4
4    5

In [17]:
#series from dataframe
series2 = dataframe2['num']
series2

0    1
1    2
2    3
3    4
4    5
Name: num, dtype: int64

In [18]:
type(series)

pandas.core.series.Series

In [21]:
#creat dataframe from 2d data
data = [[1,2],[3,4],[5,6]]
dataframe3 = pd.DataFrame(data,columns = ['num1','num2'])
dataframe3

   num1  num2
0     1     2
1     3     4
2     5     6

In [27]:
#create a series from 2d dataframe 
series3 = dataframe3[['num1','num2']]
series3

   num1  num2
0     1     2
1     3     4
2     5     6

In [24]:
type(series3)

pandas.core.frame.DataFrame