In [2]:
import pandas as pd

In [3]:
set1 = {1,2,3,4,5,6}
set1

{1, 2, 3, 4, 5, 6}

In [4]:
series1 = pd.Series(list(set1))
series1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [17]:
dataframe = pd.DataFrame(set1,columns = ['num'])
dataframe

   num
0    1
1    2
2    3
3    4
4    5
5    6

In [18]:
series2 = dataframe['num']
series2

0    1
1    2
2    3
3    4
4    5
5    6
Name: num, dtype: int64

In [25]:
tuple = (6,7,8,9,True,False)
tuple

(6, 7, 8, 9, True, False)

In [26]:
series2 = pd.Series(tuple)
series2

0        6
1        7
2        8
3        9
4     True
5    False
dtype: object

In [27]:
dataframe2 = pd.DataFrame(tuple,columns = ['Value'])
dataframe2

   Value
0      6
1      7
2      8
3      9
4   True
5  False